### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by drgogeta86**
By default the max size of ``VARCHAR2`` is 4000 but for some column need 8192 like ``API_TEST_PATH``

You need to configure your database acordingly before you start.

### CODE REVIEW

**Comment by drgogeta86** [comment]
I dunno if it worth to open an Issue too

**Comment by andrewdavidmackenzie** [comment]
@drgogeta86 This repo is a "snapshot" repo of the output of a build process from Operator repo that generates the templates. You should work there to get any changes into the code that *generates* the templates. Then close this PR?

thanks.

**Comment by hallelujah** [comment]
@drgogeta86 we require Oracle to be set up with `ALTER SYSTEM SET max_string_size=extended SCOPE=SPFILE;`

So the maximum size of VARCHAR2 : 32767 bytes.

Preferably close this PR, or update the README.md according to https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.4/html/infrastructure/building_a_3scale_api_management_system_image_with_the_oracle_database_relational_database_management_system#preparing-odb

**Comment by drgogeta86** [comment]
Updated README.md

**Pull request merged**
