### PR TITLE
Use redhat.registry for 3scale gateway name

### PR DESCRIPTION
**Pull request by VinayBhalerao**
updated 3scale gateway image name to use registry.access.redhat.com

### CODE REVIEW

**Comment by rnc** [comment]
@VinayBhalerao @andrewdavidmackenzie  According to [this](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/#registry_options) we don't normally add the direct links.

**Comment by andrewdavidmackenzie** [comment]
Thanks @rnc 

So, it won't be a problem with the final productized versions running on RHEL.

**Comment by rnc** [comment]
@andrewdavidmackenzie Shall we close this PR then?

**Comment by VinayBhalerao** [comment]
Yes please. Thank you.

**Pull request closed without merging**
